In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
df = pd.read_csv(r"C:\Users\user\Downloads\Messy_Employee_dataset.csv")

In [5]:
df1 = df.copy()

In [48]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                1020 non-null   int32
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   object
 7   Salary             1020 non-null   float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   object
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(1), int32(1), object(9)
memory usage: 84.8+ KB

In [9]:
df1.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [28]:
df1.isna().sum()

Employee_ID          0
First_Name           0
Last_Name            0
Age                  0
Department_Region    0
Status               0
Join_Date            0
Salary               0
Email                0
Phone                0
Performance_Score    0
Remote_Work          0
dtype: int64

In [25]:
df1[['Age','Salary']].describe()

               Age         Salary
count  1020.000000     996.000000
mean     31.970588   85155.056396
std       5.136901   19873.727918
min      25.000000   50047.320000
25%      30.000000   68392.487500
50%      30.000000   85547.870000
75%      35.000000  100974.027500
max      40.000000  119971.650000

In [11]:
df1["Age"].skew()

0.01795991886995613

In [12]:
df1["Age"] = df1["Age"].fillna(df1["Age"].median())

In [14]:
df1["Age"] = df1["Age"].astype(int)

In [26]:
df1["Salary"].skew()

-0.01882464568403385

In [27]:
df1["Salary"] = df1["Salary"].fillna(df1["Salary"].mean())

In [29]:
df1.duplicated().sum()

0

In [37]:
df1["Employee_ID"].nunique()

1020

In [35]:
df1["First_Name"].unique()

array(['Bob', 'Alice', 'Eva', 'Frank', 'Charlie', 'David', 'Heidi',
       'Grace'], dtype=object)

In [38]:
df1["Last_Name"].value_counts()

Brown       148
Garcia      136
Smith       136
Jones       131
Davis       120
Johnson     118
Miller      116
Williams    115
Name: Last_Name, dtype: int64

In [39]:
df1["Age"].value_counts()

30    416
40    210
25    206
35    188
Name: Age, dtype: int64

In [40]:
df1["Department_Region"].value_counts()

HR-Florida               41
DevOps-California        35
Sales-Nevada             35
Admin-Nevada             34
Admin-California         34
DevOps-Florida           34
Sales-Florida            33
DevOps-Illinois          33
HR-New York              33
Finance-Illinois         33
DevOps-New York          33
Finance-California       32
Sales-California         31
Sales-Illinois           30
Cloud Tech-Texas         29
Admin-Illinois           29
Finance-Nevada           29
Cloud Tech-California    29
Finance-Texas            29
Cloud Tech-Florida       28
DevOps-Texas             27
DevOps-Nevada            27
HR-California            26
Sales-New York           26
Admin-Florida            25
HR-Nevada                24
HR-Illinois              24
Cloud Tech-New York      24
Finance-Florida          24
HR-Texas                 23
Finance-New York         23
Sales-Texas              23
Admin-New York           22
Admin-Texas              22
Cloud Tech-Nevada        20
Cloud Tech-Illinois      16
Name: Department_Region, dtype: int64

In [41]:
df1["Status"].value_counts()

Pending     356
Active      352
Inactive    312
Name: Status, dtype: int64

In [60]:
df1["Join_Date"].unique()

array(['4/2/2021', '7/10/2020', '12/7/2023', '11/27/2021', '1/5/2022',
       '6/10/2020', '4/3/2020', '7/17/2022', '12/8/2023', '8/4/2022',
       '7/6/2024', '9/4/2023', '3/5/2024', '10/10/2020', '6/10/2024',
       '5/29/2021', '4/23/2024', '11/28/2024', '9/19/2024', '1/2/2020',
       '5/8/2021', '9/19/2020', '3/9/2021', '2/3/2022', '2/13/2020',
       '4/30/2020', '10/2/2023', '7/12/2020', '10/11/2023', '5/24/2021',
       '5/26/2021', '11/5/2024', '8/7/2021', '4/29/2020', '10/26/2022',
       '5/3/2023', '5/2/2023', '10/5/2021', '7/27/2022', '6/27/2021',
       '6/16/2022', '12/3/2024', '5/23/2023', '7/8/2020', '6/20/2021',
       '12/13/2024', '5/30/2022', '9/27/2023', '11/11/2021', '2/22/2022',
       '8/7/2024', '11/9/2021', '8/10/2020', '2/27/2022', '11/7/2023',
       '11/7/2021', '4/16/2022', '10/19/2023', '8/10/2021', '3/13/2021',
       '7/20/2023', '2/20/2020', '2/2/2021', '1/12/2020', '11/26/2022',
       '12/23/2022', '8/28/2024', '9/16/2024', '1/1/2024', '4/18/2021',
       '1/16/2023', '10/20/2024', '10/13/2024', '9/21/2022', '12/29/2022',
       '11/10/2024', '11/22/2021', '3/14/2024', '3/23/2020', '9/15/2020',
       '12/9/2020', '2/22/2020', '4/27/2023', '6/18/2024', '5/21/2020',
       '7/25/2023', '8/25/2023', '7/3/2021', '3/13/2023', '3/10/2021',
       '1/21/2020', '11/15/2023', '4/8/2022', '5/21/2022', '4/17/2021',
       '3/19/2021', '1/9/2022', '8/21/2021', '8/19/2022', '3/31/2022',
       '6/23/2020', '5/7/2024', '3/10/2023', '9/14/2023', '11/12/2023',
       '10/26/2024', '8/23/2020', '6/11/2024', '9/14/2021', '12/26/2024',
       '9/8/2024', '8/21/2022', '7/25/2024', '8/2/2020', '3/16/2020',
       '9/8/2023', '3/29/2024', '8/12/2021', '12/24/2023', '8/28/2020',
       '9/5/2024', '5/12/2023', '7/1/2021', '11/7/2024', '7/21/2022',
       '3/30/2020', '10/11/2022', '7/24/2022', '6/30/2023', '1/11/2024',
       '11/2/2023', '11/22/2024', '8/23/2021', '4/9/2023', '7/5/2024',
       '9/4/2021', '2/14/2020', '4/10/2020', '7/27/2023', '9/24/2021',
       '3/10/2024', '6/10/2021', '10/15/2020', '1/29/2020', '1/30/2022',
       '3/29/2021', '10/13/2020', '10/4/2020', '12/18/2024', '11/14/2023',
       '1/20/2023', '10/2/2024', '5/13/2021', '3/18/2021', '9/23/2020',
       '6/5/2024', '2/28/2024', '4/30/2023', '3/4/2020', '12/29/2023',
       '7/18/2022', '7/13/2022', '10/2/2021', '7/5/2020', '4/16/2023',
       '11/12/2024', '3/29/2023', '1/22/2022', '10/14/2023', '4/10/2024',
       '2/9/2022', '5/6/2023', '7/11/2021', '8/21/2020', '3/27/2021',
       '4/14/2024', '9/21/2020', '6/12/2022', '7/31/2022', '4/21/2023',
       '6/5/2020', '7/27/2024', '4/5/2024', '10/26/2023', '8/18/2022',
       '5/31/2020', '11/4/2024', '3/25/2020', '11/4/2020', '3/21/2020',
       '1/15/2022', '6/4/2024', '8/4/2021', '10/16/2020', '9/26/2021',
       '11/4/2023', '6/7/2020', '2/10/2022', '10/17/2023', '9/25/2021',
       '8/3/2022', '10/9/2024', '4/19/2020', '10/14/2021', '8/26/2024',
       '2/8/2020', '9/6/2020', '1/2/2023', '6/13/2023', '12/13/2022',
       '3/3/2022', '2/10/2024', '11/24/2021', '5/9/2020', '12/19/2024',
       '3/22/2024', '6/13/2022', '10/15/2022', '5/31/2022', '9/15/2023',
       '7/4/2022', '6/8/2024', '11/23/2020', '5/13/2024', '1/29/2022',
       '8/23/2023', '2/24/2023', '10/2/2022', '6/28/2020', '1/15/2023',
       '9/5/2020', '3/18/2023', '3/26/2022', '10/11/2021', '1/7/2021',
       '12/3/2020', '5/28/2021', '12/28/2022', '5/24/2023', '4/28/2024',
       '12/25/2024', '9/1/2021', '2/21/2021', '11/20/2022', '7/24/2024',
       '8/14/2022', '10/9/2023', '1/19/2022', '1/12/2022', '6/5/2023',
       '3/26/2024', '10/7/2020', '11/2/2021', '11/19/2021', '1/24/2022',
       '7/12/2023', '12/9/2022', '4/25/2022', '2/28/2021', '7/30/2022',
       '5/19/2021', '12/14/2023', '1/17/2023', '1/2/2024', '7/9/2021',
       '5/5/2021', '8/30/2023', '8/15/2023', '12/24/2020', '11/21/2024',
       '11/17/2021', '1/29/2021', '2/17/2024', '8/20/2024', '10/24/2021',
       '9/10/2021', '9/29/2023', '9/6/2022', '3/31/2024', '12/12/2022',
       '11/1/2022', '10/25/2023', '9/27/2020', '1/21/2024', '5/17/2022',
       '4/17/2022', '2/8/2022', '3/15/2022', '11/13/2020', '4/17/2024',
       '3/9/2020', '6/17/2022', '7/28/2024', '12/3/2022', '7/6/2023',
       '5/28/2024', '3/25/2024', '4/28/2020', '4/15/2020', '10/7/2023',
       '2/27/2024', '2/22/2021', '8/21/2023', '4/8/2024', '5/5/2022',
       '2/1/2023', '10/1/2022', '9/27/2022', '4/9/2020', '3/23/2021',
       '2/3/2023', '7/23/2024', '4/11/2022', '10/23/2024', '4/24/2020',
       '3/4/2023', '8/31/2022', '1/2/2021', '6/6/2020', '7/19/2020',
       '5/3/2024', '2/7/2022', '12/31/2023', '1/8/2022', '9/28/2020',
       '2/9/2023', '3/5/2022', '2/18/2022', '6/9/2022', '7/4/2023',
       '3/21/2022', '10/15/2021', '7/28/2021', '1/3/2021', '5/10/2021',
       '9/8/2022', '7/21/2024', '12/28/2021', '7/20/2020', '4/30/2024',
       '8/28/2021', '11/27/2023', '8/11/2020', '11/8/2021', '8/4/2023',
       '1/10/2020', '5/7/2023', '12/19/2020', '10/1/2020', '11/12/2022',
       '1/5/2023', '10/14/2020', '2/3/2021', '12/25/2023', '3/7/2020',
       '1/30/2023', '6/15/2023', '7/29/2021', '10/23/2023', '10/18/2020',
       '6/15/2024', '4/6/2023', '1/3/2022', '7/23/2022', '11/25/2024',
       '12/12/2023', '10/24/2023', '9/5/2022', '1/18/2020', '4/23/2022',
       '4/22/2023', '8/13/2023', '10/10/2022', '4/11/2024', '10/23/2022',
       '10/31/2021', '9/29/2024', '4/22/2020', '12/7/2020', '4/23/2020',
       '10/12/2023', '8/24/2022', '2/2/2022', '4/1/2022', '4/26/2023',
       '4/19/2022', '10/4/2024', '5/2/2020', '7/29/2023', '8/20/2021',
       '4/23/2021', '8/12/2022', '6/26/2021', '10/30/2020', '1/31/2023',
       '9/24/2020', '3/28/2020', '10/31/2023', '3/11/2020', '5/4/2020',
       '7/15/2023', '4/19/2024', '6/29/2021', '9/14/2024', '1/4/2022',
       '1/20/2021', '3/18/2020', '11/10/2021', '5/1/2020', '2/4/2022',
       '11/18/2020', '11/21/2023', '2/13/2022', '3/19/2023', '3/28/2021',
       '5/2/2021', '3/5/2021', '3/1/2022', '1/23/2023', '8/26/2021',
       '11/25/2020', '12/13/2023', '7/26/2020', '6/16/2020', '4/1/2020',
       '3/20/2024', '2/7/2023', '12/10/2024', '6/27/2024', '8/11/2024',
       '4/19/2023', '11/11/2024', '3/17/2023', '7/4/2021', '11/3/2023',
       '7/5/2021', '2/26/2024', '9/29/2021', '5/25/2021', '10/31/2022',
       '7/2/2022', '10/21/2024', '2/11/2020', '5/16/2023', '7/29/2022',
       '9/18/2023', '5/10/2020', '8/27/2023', '10/16/2021', '3/6/2022',
       '11/6/2023', '11/30/2024', '7/13/2024', '3/4/2024', '8/7/2022',
       '12/2/2021', '5/14/2024', '7/14/2022', '9/22/2020', '2/24/2022',
       '1/30/2024', '3/16/2024', '9/25/2020', '4/8/2020', '6/28/2022',
       '7/14/2023', '12/6/2023', '8/1/2021', '2/17/2021', '11/10/2023',
       '9/6/2024', '7/23/2020', '2/21/2024', '12/15/2020', '4/24/2023',
       '6/6/2023', '6/21/2022', '4/20/2024', '12/5/2023', '8/6/2023',
       '7/31/2024', '8/31/2020', '2/15/2023', '3/30/2021', '8/5/2020',
       '2/5/2021', '11/23/2021', '10/29/2022', '11/7/2022', '5/14/2023',
       '7/14/2021', '5/18/2023', '8/24/2023', '4/8/2023', '12/6/2022',
       '8/9/2021', '5/25/2024', '7/21/2023', '10/30/2023', '2/13/2023',
       '5/19/2020', '9/20/2023', '8/13/2024', '6/10/2023', '6/9/2021',
       '5/2/2024', '11/6/2024', '8/17/2023', '6/13/2021', '10/10/2023',
       '1/2/2022', '2/20/2022', '3/9/2024', '8/19/2023', '1/26/2024',
       '5/29/2020', '1/31/2021', '1/16/2022', '12/2/2024', '12/20/2024',
       '3/31/2023', '5/4/2021', '1/1/2021', '10/25/2021', '12/22/2020',
       '11/23/2022', '10/24/2022', '8/20/2020', '2/15/2020', '12/29/2024',
       '2/28/2023', '8/23/2022', '4/15/2021', '5/9/2022', '5/20/2023',
       '11/29/2023', '10/25/2024', '3/2/2024', '2/24/2021', '4/13/2023',
       '9/17/2022', '10/7/2024', '11/22/2022', '4/15/2023', '7/20/2022',
       '2/18/2023', '5/27/2021', '8/1/2022', '3/13/2024', '3/20/2023',
       '2/15/2024', '11/15/2020', '3/27/2020', '1/9/2021', '4/20/2020',
       '5/8/2024', '1/28/2023', '3/7/2021', '3/16/2023', '2/11/2023',
       '5/13/2022', '10/24/2024', '5/25/2023', '11/11/2022', '7/17/2023',
       '4/17/2023', '4/25/2021', '7/14/2020', '7/31/2020', '10/28/2024',
       '10/3/2020', '1/1/2020', '3/19/2022', '5/14/2022', '7/14/2024',
       '7/28/2023', '4/11/2020', '5/10/2022', '6/13/2020', '8/20/2022',
       '4/27/2024', '10/23/2021', '2/10/2021', '10/26/2021', '4/5/2023',
       '10/20/2022', '1/23/2024', '11/28/2023', '2/11/2024', '7/16/2020',
       '4/23/2023', '12/27/2024', '8/10/2024', '9/4/2024', '2/28/2022',
       '4/24/2022', '3/14/2021', '9/7/2021', '11/13/2022', '3/14/2023',
       '8/18/2024', '2/5/2024', '4/13/2020', '8/28/2023', '1/25/2021',
       '8/9/2024', '6/25/2023', '9/16/2021', '12/7/2022', '12/14/2022',
       '4/18/2020', '10/11/2024', '6/29/2020', '5/21/2021', '12/11/2021',
       '7/5/2023', '11/30/2021', '6/26/2024', '11/19/2020', '3/1/2020',
       '1/13/2021', '10/25/2022', '10/8/2020', '2/29/2024', '9/30/2022',
       '2/14/2024', '1/3/2023', '12/16/2024', '4/21/2020', '8/19/2020',
       '2/21/2020', '11/17/2023', '7/9/2022', '11/14/2024', '6/29/2023',
       '12/12/2024', '11/26/2020', '3/14/2020', '5/12/2020', '2/2/2024',
       '7/30/2021', '3/28/2023', '11/25/2021', '4/27/2022', '9/11/2021',
       '11/24/2024', '3/6/2024', '10/15/2023', '5/5/2023', '8/1/2024',
       '7/22/2024', '3/13/2022', '5/13/2020', '3/22/2023', '11/21/2020',
       '9/19/2023', '10/28/2021', '5/5/2020', '12/24/2022', '9/5/2021',
       '1/29/2023', '6/3/2022', '1/21/2023', '2/2/2020', '7/8/2024',
       '5/18/2022', '1/16/2020', '3/26/2023', '3/21/2023', '5/8/2023',
       '12/12/2020', '6/17/2020', '7/17/2021', '11/5/2020', '1/5/2021',
       '9/11/2024', '4/17/2020', '2/16/2022', '8/14/2021', '7/7/2021',
       '2/12/2024', '7/7/2020', '9/2/2020', '1/12/2021', '2/14/2021',
       '5/24/2020', '3/12/2022', '5/18/2024', '9/18/2024', '6/15/2022',
       '9/28/2022', '9/28/2023', '3/25/2023', '7/1/2020', '9/16/2020',
       '12/13/2021', '1/11/2022', '7/20/2021', '10/4/2023', '11/15/2021',
       '1/17/2024', '4/16/2021', '6/2/2023', '1/30/2020', '3/31/2021',
       '7/16/2024', '6/1/2024', '12/23/2024', '10/28/2022', '11/20/2023',
       '3/11/2022', '5/3/2022', '2/19/2024', '11/18/2021', '12/21/2022',
       '7/22/2022', '10/10/2021', '3/12/2020', '9/7/2022', '10/5/2024',
       '10/12/2021', '10/14/2024', '7/1/2022', '10/21/2020', '1/14/2020',
       '3/9/2023', '4/4/2021', '9/11/2020', '5/16/2021', '11/15/2022',
       '10/22/2021', '8/3/2024', '5/15/2020', '2/13/2021', '8/5/2024',
       '1/9/2020', '11/30/2023', '10/5/2020', '10/22/2023', '9/10/2023',
       '4/15/2024', '8/27/2024', '11/8/2020', '8/24/2021', '2/6/2020',
       '10/12/2024', '4/13/2024', '10/18/2021', '2/25/2020', '6/22/2020',
       '1/7/2023', '11/26/2021', '9/17/2024', '7/13/2021', '12/11/2023',
       '7/2/2021', '12/5/2022', '9/24/2024', '8/16/2023', '1/28/2021'],
      dtype=object)

In [42]:
df["Email"].nunique()

64

In [43]:
df1["Phone"].nunique()

1020

In [44]:
df1["Performance_Score"].value_counts()

Good         270
Average      267
Excellent    267
Poor         216
Name: Performance_Score, dtype: int64

In [45]:
df1["Remote_Work"].value_counts()

True     513
False    507
Name: Remote_Work, dtype: int64

In [47]:
df1["Phone"] = df1["Phone"].astype(str)

In [50]:
df1.to_csv("clean_employee_dataset.csv",index=False,mode="x")

In [51]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                1020 non-null   int32
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   object
 7   Salary             1020 non-null   float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   object
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(1), int32(1), object(9)
memory usage: 84.8+ KB

In [52]:
 df1.tail()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
1015,EMP2015,David,Miller,30,HR-California,Active,8/19/2023,85155.056396,david.miller@example.com,-3546212759,Good,True
1016,EMP2016,David,Johnson,30,Cloud Tech-Texas,Inactive,11/7/2021,100215.060000,david.johnson@example.com,-2508261122,Good,True
1017,EMP2017,Charlie,Williams,40,Finance-New York,Active,10/4/2023,114587.110000,charlie.williams@example.com,-1261632487,Average,False
1018,EMP2018,Alice,Garcia,30,HR-Florida,Inactive,12/16/2024,71318.790000,alice.garcia@example.com,-8995729892,Good,True
1019,EMP2019,Heidi,Jones,30,DevOps-Illinois,Pending,2/22/2021,77764.240000,heidi.jones@example.com,-7629745492,Average,False

In [2]:
import pandas as pd

In [9]:
df = pd.read_csv(r"C:\Users\user\Desktop\project\clean_employee_dataset.csv")
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,30,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,30,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [5]:
df1 = df.copy()

In [11]:
df1["Join_Date"] = pd.to_datetime(df1["Join_Date"],errors="coerce")

In [14]:
df1.to_csv(r"C:\Users\user\Desktop\project\clean_employee_dataset.csv",index=False)